### ISSUE TITLE
AssertionError: Sparse4D: Sparse4DHead: DeformableFeatureAggregation: deformable_aggregation needs to be set up. (Conda env))

### ISSUE THREAD

**Issue by andrew403** [HorizonRobotics/Sparse4D#67]
Hello, I have been going through the quick setup but got some errors when I'm running 'bash local_train.sh sparse4dv3_temporal_r50_1x8_bs6_256x704':

Traceback (most recent call last):
  File "./tools/train.py", line 318, in <module>
    main()
  File "./tools/train.py", line 263, in main
    model = build_detector(
  File "/home/liu/anaconda3/envs/mm_sparse4d/lib/python3.8/site-packages/mmdet/models/builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "/home/liu/anaconda3/envs/mm_sparse4d/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/liu/anaconda3/envs/mm_sparse4d/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/liu/anaconda3/envs/mm_sparse4d/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: Sparse4D: Sparse4DHead: DeformableFeatureAggregation: deformable_aggregation needs to be set up.

I've also tried to recompile according to the solution from the previous solved issue, but it still won't fix the problem, instead, I cannot recompile anymore, showing error below:
TypeError: expected string or bytes-like object

However, I am running under the conda environment instead of virtualenv, would this be the reason why? Thanks.

**Comment by linxuewu** [comment]
![image](https://github.com/HorizonRobotics/Sparse4D/assets/50012935/e21c7912-d539-44a0-b49b-9e1edbe2d171)

**Comment by andrew403** [comment]
Hi, but this is what I did and still get these errors while running training, is there anything I need to be aware of?

**Comment by linxuewu** [comment]
I think it may not be compiled successfully?

**Comment by andrew403** [comment]
Okay so I eventually solved it by editing my CUDA path, it seems that there was something wrong with my environment variables. Thank you so much for your help!
