### ISSUE TITLE
Cannot train on multiple GPUs using `dist_train.sh`

### ISSUE THREAD

**Issue by yizhou-wang** [HorizonRobotics/Sparse4D#92]
Thanks a lot for the open-source code! 

I'm trying to train the model on multiple GPUs using the script dist_train.sh, but I got some errors. Here are my working logs.

I'm currently using pytorch 2.1, cuda 12.1. **Everything is working well using `tools/train.py` script on single GPU.**
```python tools/train.py <CONFIG>```

I did the following to deploy it on **multiple GPUs** based `dist_train.sh`:

1. Change `python3 -m torch.distributed.launch` to `torchrun`. Then I got the following error:
```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 1: 646 647 648 649 650 651
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
```

2. Add `find_unused_parameters=True` to config file. Then I got the following:
```
Traceback (most recent call last):
  File "tools/train.py", line 320, in <module>
    main()
  File "tools/train.py", line 295, in main
    custom_train_model(
  File "/home/yizwang/projects/BEVMTMC/sparse4d/./projects/mmdet3d_plugin/apis/train.py", line 29, in custom_train_model
    custom_train_detector(
  File "/home/yizwang/projects/BEVMTMC/sparse4d/./projects/mmdet3d_plugin/apis/mmdet_train.py", line 219, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/yizwang/projects/BEVMTMC/dependencies/mmcv/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/yizwang/projects/BEVMTMC/dependencies/mmcv/mmcv/runner/iter_based_runner.py", line 70, in train
    self.call_hook('after_train_iter')
  File "/home/yizwang/projects/BEVMTMC/dependencies/mmcv/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/yizwang/projects/BEVMTMC/dependencies/mmcv/mmcv/runner/hooks/optimizer.py", line 290, in after_train_iter
    self.loss_scaler.scale(runner.outputs['loss']).backward()
  File "/usr/local/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/usr/local/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 288, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 157 with name img_backbone.layer4.2.bn3.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
```

Note that this error occurs even when I set number of GPUs to 1:
```
bash tools/dist_train.sh <CONFIG> 1
```

Could anyone help with this problem? Thanks!

**Comment by linxuewu** [comment]
1. Set `export TORCH_DISTRIBUTED_DEBUG=INFO` to see which parameters are unused, and then ensure these parameters are actually being used. 

2. The reason enabling `find_unused_parameters` causes an error is that `checkpoint` is being used, and `checkpoint` cannot be used simultaneously with find_unused_parameters. You can try turning off all `checkpoint`, such as setting `with_cp=False` in the backbone config.

**Comment by yizhou-wang** [comment]
@linxuewu Resolved. Thanks a lot for the help!
